# libvirt_uri: qemu:///system
# libvirt_volume_pool: default
# libvirt_volume_path: /var/lib/libvirt/images

release: master

# installer_image_url: file:///home/{{ non_root_user}}/rhel-atomic-cloud-7.3.5-7.x86_64.qcow2
installer_image_url: file:///home/{{ non_root_user}}/CentOS-7-x86_64-GenericCloud.qcow2
installer_key: "{{ local_working_dir }}/id_rsa_installer"
undercloud_key: "{{ local_working_dir }}/id_rsa_installer"
virt_power_key: "{{ local_working_dir }}/id_rsa_virt_power"
inject_instackenv: true

images:
  - name: installer
    url: "{{ installer_image_url }}"
    type: qcow2

default_memory: 4096
undercloud_memory: 12288

default_vcpu: 2
undercloud_vcpu: 4

overcloud_nodes:
  - name: baremetal_0
    flavor: baremetal
    virtualbmc_port: 6234
  - name: baremetal_1
    flavor: baremetal
    virtualbmc_port: 6235
  - name: baremetal_2
    flavor: baremetal
    virtualbmc_port: 6236
  - name: baremetal_3
    flavor: baremetal
    virtualbmc_port: 6237

installer_node:
  name: installer
  flavor: installer

flavors:
  installer:
    memory: 8192
    disk: 40
    vcpu: 4
  baremetal:
    memory: 4096
    disk: 40
    vcpu: 2

networks:
  - name: external
    bridge: brext
    forward_mode: nat
    address: "{{ external_network_cidr|nthhost(1) }}"
    netmask: "{{ external_network_cidr|ipaddr('netmask') }}"
    dhcp_range:
      - "{{ external_network_cidr|nthhost(10) }}"
      - "{{ external_network_cidr|nthhost(50) }}"
    nat_port_range:
      - 1024
      - 65535

  - name: provisioning
    bridge:  provisioning
