# This is the playbook used by the `quickstart.sh` script.

# Add the virthost to the in-memory inventory. The inventory is not
# written out to disk unless you call the `tripleo-inventory` role.
- name: Add the virthost to the inventory
  hosts: localhost
  tasks:
    - name: Add virthost
      add_host:
        name: "{{virthost}}"
        groups: "virthost"
        ansible_fqdn: "{{ virthost }}"
        ansible_user: "root"
        ansible_host: "{{ virthost }}"
  tags:
    - provision

# The `provision.yml` playbook is responsible for
# creating an inventory entry for our `virthost` and for creating an
# unprivileged user on that host for use by our virtual environment.
- include: tripleo-quickstart/playbooks/provision.yml

# The `environment/setup` role performs any tasks that require `root`
# access on the target host.
- name: Install libvirt packages and configure networks
  hosts: virthost
  gather_facts: yes
  tags:
    - environment
  roles:
    - environment/setup

# The `libvirt/setup` role creates the undercloud and overcloud
# virtual machines.
- name:  Setup undercloud, overcloud, and supplemental vms
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/setup/user
    - libvirt/setup/overcloud


- name: Add the undercloud node to the generated inventory
  hosts: localhost
  gather_facts: yes
  tags:
    - undercloud-scripts
  roles:
    - tripleo-inventory

- name: Setup Installer node
  hosts: virthost
  gather_facts: no
  roles:
    - libvirt
    - installer

# For some reason, when including tasks (not playbooks), the inventory and vars
# are not defined, so we need to redo some of it.
- name: Setup virtualbmc
  hosts: installer
  gather_facts: no
  vars:
    external_network_cidr: 192.168.23.0/24
  tasks:
    - name: Add virthost
      add_host:
        name: virthost
        groups: "virthost"
        ansible_fqdn: "{{ virthost }}"
        ansible_user: "root"
        ansible_host: "{{ virthost }}"
    - include: tripleo-quickstart-extras/roles/undercloud-deploy/tasks/configure-vbmc.yml
